// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404121652_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DernierInventaire")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantiteStock")
                        .HasColumnType("int");

                    b.Property<string>("TypeArticle")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasDiscriminator<string>("TypeArticle").HasValue("Article");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Inventaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AncienneQuantite")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("NouvelleQuantite")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceArticle")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Inventaires");
                });

            modelBuilder.Entity("Domain.Entities.MouvementStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceArticle")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Mouvements");
                });

            modelBuilder.Entity("Domain.Entities.ArticleAlimentaire", b =>
                {
                    b.HasBaseType("Domain.Entities.Article");

                    b.Property<DateTime>("DLC")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeVente")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Alimentaire");
                });

            modelBuilder.Entity("Domain.Entities.ArticleNonAlimentaire", b =>
                {
                    b.HasBaseType("Domain.Entities.Article");

                    b.Property<int>("Packaging")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("NonAlimentaire");
                });

            modelBuilder.Entity("Domain.Entities.Article", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Prix", "PrixHT", b1 =>
                        {
                            b1.Property<int>("ArticleId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Valeur")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PrixHT");

                            b1.HasKey("ArticleId");

                            b1.ToTable("Articles");

                            b1.WithOwner()
                                .HasForeignKey("ArticleId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Prix", "PrixTTC", b1 =>
                        {
                            b1.Property<int>("ArticleId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Valeur")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PrixTTC");

                            b1.HasKey("ArticleId");

                            b1.ToTable("Articles");

                            b1.WithOwner()
                                .HasForeignKey("ArticleId");
                        });

                    b.OwnsOne("Domain.ValueObjects.ReferenceEAN13", "Reference", b1 =>
                        {
                            b1.Property<int>("ArticleId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(13)
                                .HasColumnType("nvarchar(13)")
                                .HasColumnName("Reference");

                            b1.HasKey("ArticleId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Articles");

                            b1.WithOwner()
                                .HasForeignKey("ArticleId");
                        });

                    b.Navigation("PrixHT")
                        .IsRequired();

                    b.Navigation("PrixTTC")
                        .IsRequired();

                    b.Navigation("Reference")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.MouvementStock", b =>
                {
                    b.HasOne("Domain.Entities.Article", null)
                        .WithMany("Mouvements")
                        .HasForeignKey("ArticleId");
                });

            modelBuilder.Entity("Domain.Entities.Article", b =>
                {
                    b.Navigation("Mouvements");
                });
#pragma warning restore 612, 618
        }
    }
}
